from graphics import cuboid32,sphere32,rectangle32,circle32
r=int(input("enter the radius of circle:"))
circle32.areac(r)
circle32.peric(r)
l=int(input("enter the length of rectangle:"))
b=int(input("enter the breadth of rectangle:"))
rectangle32.arear(l,b)
rectangle32.perir(l,b)
l1=int(input("enter the length of cuboid:"))
b1=int(input("enter the breadth of cuboid:"))
h1=int(input("enter the height of cuboid:"))
cuboid32.areacub(l1,b1,h1)
cuboid32.pericub(l1,b1,h1)
r1=int(input("enter the radius of sphere:"))
sphere32.areas(r1)
sphere32.peris(r1)